#!/usr/bin/env bash
# Copyright (C) 2021-2024 Bytedance Ltd. and/or its affiliates

chmod 755 /opt/openlava-2.0/lib/liblsf.a || true
chmod 755 /opt/openlava-2.0/lib/liblsbatch.a || true

chmod 755 /etc/profile.d/openlava.sh || true
chmod 755 /etc/profile.d/openlava.csh || true
chmod 755 /opt/openlava-2.0/etc/openlava.sh || true
chmod 755 /opt/openlava-2.0/etc/openlava.csh || true

source /etc/profile.d/openlava.sh || true

chmod 755 /etc/init.d/openlava || true
chmod 755 /opt/openlava-2.0/etc/openlava || true

groupadd -f openlava || true
useradd -c "openlava Administrator" -g openlava -m -d /home/openlava openlava || true

chown -R openlava:openlava /opt/openlava-2.0/*
chgrp -R openlava /opt/openlava-2.0/*